name: Slack Notification
on:
  workflow_run:
    workflows:
      - Jest
    types:
      - completed
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Success: <${{ github.event.workflow.html_url }}|${{ github.event.workflow.name }}>\n${{ github.event.workflow_run.head_commit.message }} <${{ github.event.workflow_run.html_url }}|action> <https://github.com/${{ github.repository }}/commit/${{ github.event.workflow_run.head_commit.message }}|commit>"
                  }
                }
              ]            }
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: dump context
        run: echo '${{ toJSON(github) }}'          
