name: NodeJS with Webpack

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Build
        run: |
          yarn install
          yarn run build

      - name: Test
        run: npx jest
      - uses: actions/github-script@v6
        with:
          script: |
            core.info(JSON.stringify(job))
      - uses: actions/github-script@v6
        with:
          script: |
            core.info(JSON.stringify(github))            
